using System;
using System.Xml.Serialization;
using System.ComponentModel;
using InvoiceXpressDotNet.Extensions;

namespace InvoiceXpressDotNet
{
	public enum Country
	{
		[XmlEnum("")]
		None = 0,
		[XmlEnum(Name="Portugal")]
		Portugal,
		[XmlEnum(Name="Ireland")]
		Ireland,
		[XmlEnum(Name="UK")]
		UK,
		[XmlEnum(Name="Canada")]
		Canada,
		[XmlEnum(Name="UnitedStates")]
		UnitedStates,
		[XmlEnum(Name="Afghanistan")]
		Afghanistan,
		[XmlEnum(Name="Albania")]
		Albania,
		[XmlEnum(Name="Algeria")]
		Algeria,
		[XmlEnum(Name="AmericanSamoa")]
		AmericanSamoa,
		[XmlEnum(Name="Andorra")]
		Andorra,
		[XmlEnum(Name="Angola")]
		Angola,
		[XmlEnum(Name="Anguilla")]
		Anguilla,
		[XmlEnum(Name="AntiguaAndBarbuda")]
		AntiguaAndBarbuda,
		[XmlEnum(Name="Argentina")]
		Argentina,
		[XmlEnum(Name="Armenia")]
		Armenia,
		[XmlEnum(Name="Aruba")]
		Aruba,
		[XmlEnum(Name="Australia")]
		Australia,
		[XmlEnum(Name="Austria")]
		Austria,
		[XmlEnum(Name="Azerbaijan")]
		Azerbaijan,
		[XmlEnum(Name="Bahamas")]
		Bahamas,
		[XmlEnum(Name="Bahrain")]
		Bahrain,
		[XmlEnum(Name="Bangladesh")]
		Bangladesh,
		[XmlEnum(Name="Barbados")]
		Barbados,
		[XmlEnum(Name="Belarus")]
		Belarus,
		[XmlEnum(Name="Belgium")]
		Belgium,
		[XmlEnum(Name="Belize")]
		Belize,
		[XmlEnum(Name="Benin")]
		Benin,
		[XmlEnum(Name="Bermuda")]
		Bermuda,
		[XmlEnum(Name="Bhutan")]
		Bhutan,
		[XmlEnum(Name="Bolivia")]
		Bolivia,
		[XmlEnum(Name="BosniaHerzegovina")]
		BosniaHerzegovina,
		[XmlEnum(Name="Botswana")]
		Botswana,
		[XmlEnum(Name="Brazil")]
		Brazil,
		[XmlEnum(Name="BritishIndianOceanTerritory")]
		BritishIndianOceanTerritory,
		[XmlEnum(Name="Brunei")]
		Brunei,
		[XmlEnum(Name="Bulgaria")]
		Bulgaria,
		[XmlEnum(Name="BurkinaFaso")]
		BurkinaFaso,
		[XmlEnum(Name="Burma")]
		Burma,
		[XmlEnum(Name="Burundi")]
		Burundi,
		[XmlEnum(Name="Cambodia")]
		Cambodia,
		[XmlEnum(Name="Cameroon")]
		Cameroon,
		[XmlEnum(Name="CantonAndEnderburyIslands")]
		CantonAndEnderburyIslands,
		[XmlEnum(Name="CapeVerde")]
		CapeVerde,
		[XmlEnum(Name="CaymanIslands")]
		CaymanIslands,
		[XmlEnum(Name="CentralAfricanRepublic")]
		CentralAfricanRepublic,
		[XmlEnum(Name="Chad")]
		Chad,
		[XmlEnum(Name="Chile")]
		Chile,
		[XmlEnum(Name="China")]
		China,
		[XmlEnum(Name="ChristmasIsland")]
		ChristmasIsland,
		[XmlEnum(Name="CocosKeelingIslands")]
		CocosKeelingIslands,
		[XmlEnum(Name="Colombia")]
		Colombia,
		[XmlEnum(Name="Comoros")]
		Comoros,
		[XmlEnum(Name="Congo")]
		Congo,
		[XmlEnum(Name="CongoDemocraticRepublic")]
		CongoDemocraticRepublic,
		[XmlEnum(Name="CookIslands")]
		CookIslands,
		[XmlEnum(Name="CostaRica")]
		CostaRica,
		[XmlEnum(Name="CoteDIvoire")]
		CoteDIvoire,
		[XmlEnum(Name="Croatia")]
		Croatia,
		[XmlEnum(Name="Cuba")]
		Cuba,
		[XmlEnum(Name="Curacao")]
		Curacao,
		[XmlEnum(Name="Cyprus")]
		Cyprus,
		[XmlEnum(Name="CzechRepublic")]
		CzechRepublic,
		[XmlEnum(Name="Denmark")]
		Denmark,
		[XmlEnum(Name="Djibouti")]
		Djibouti,
		[XmlEnum(Name="Dominica")]
		Dominica,
		[XmlEnum(Name="DominicanRepublic")]
		DominicanRepublic,
		[XmlEnum(Name="DronningMaudLand")]
		DronningMaudLand,
		[XmlEnum(Name="EastTimor")]
		EastTimor,
		[XmlEnum(Name="Ecuador")]
		Ecuador,
		[XmlEnum(Name="Egypt")]
		Egypt,
		[XmlEnum(Name="ElSalvador")]
		ElSalvador,
		[XmlEnum(Name="EquatorialGuinea")]
		EquatorialGuinea,
		[XmlEnum(Name="Eritrea")]
		Eritrea,
		[XmlEnum(Name="Estonia")]
		Estonia,
		[XmlEnum(Name="Ethiopia")]
		Ethiopia,
		[XmlEnum(Name="FaeroeIslandsFøroyar")]
		FaeroeIslandsFøroyar,
		[XmlEnum(Name="FalklandIslands")]
		FalklandIslands,
		[XmlEnum(Name="Fiji")]
		Fiji,
		[XmlEnum(Name="Finland")]
		Finland,
		[XmlEnum(Name="France")]
		France,
		[XmlEnum(Name="FrenchGuiana")]
		FrenchGuiana,
		[XmlEnum(Name="FrenchPolynesia")]
		FrenchPolynesia,
		[XmlEnum(Name="Gabon")]
		Gabon,
		[XmlEnum(Name="Gambia")]
		Gambia,
		[XmlEnum(Name="Georgia")]
		Georgia,
		[XmlEnum(Name="Germany")]
		Germany,
		[XmlEnum(Name="Ghana")]
		Ghana,
		[XmlEnum(Name="Gibraltar")]
		Gibraltar,
		[XmlEnum(Name="GreatBritain")]
		GreatBritain,
		[XmlEnum(Name="Greece")]
		Greece,
		[XmlEnum(Name="Greenland")]
		Greenland,
		[XmlEnum(Name="Grenada")]
		Grenada,
		[XmlEnum(Name="Guadeloupe")]
		Guadeloupe,
		[XmlEnum(Name="Guam")]
		Guam,
		[XmlEnum(Name="Guatemala")]
		Guatemala,
		[XmlEnum(Name="Guernsey")]
		Guernsey,
		[XmlEnum(Name="GuineaBissau")]
		GuineaBissau,
		[XmlEnum(Name="Guinea")]
		Guinea,
		[XmlEnum(Name="Guyana")]
		Guyana,
		[XmlEnum(Name="Haiti")]
		Haiti,
		[XmlEnum(Name="HeardAndMcDonaldIslands")]
		HeardAndMcDonaldIslands,
		[XmlEnum(Name="Honduras")]
		Honduras,
		[XmlEnum(Name="HongKong")]
		HongKong,
		[XmlEnum(Name="Hungary")]
		Hungary,
		[XmlEnum(Name="Iceland")]
		Iceland,
		[XmlEnum(Name="India")]
		India,
		[XmlEnum(Name="Indonesia")]
		Indonesia,
		[XmlEnum(Name="InternationalMonetaryFund")]
		InternationalMonetaryFund,
		[XmlEnum(Name="Iran")]
		Iran,
		[XmlEnum(Name="Iraq")]
		Iraq,
		[XmlEnum(Name="IsleOfMan")]
		IsleOfMan,
		[XmlEnum(Name="Israel")]
		Israel,
		[XmlEnum(Name="Italy")]
		Italy,
		[XmlEnum(Name="IvoryCoast")]
		IvoryCoast,
		[XmlEnum(Name="Jamaica")]
		Jamaica,
		[XmlEnum(Name="Japan")]
		Japan,
		[XmlEnum(Name="Jersey")]
		Jersey,
		[XmlEnum(Name="JohnstonIsland")]
		JohnstonIsland,
		[XmlEnum(Name="Jordan")]
		Jordan,
		[XmlEnum(Name="Kampuchea")]
		Kampuchea,
		[XmlEnum(Name="Kazakhstan")]
		Kazakhstan,
		[XmlEnum(Name="Kenya")]
		Kenya,
		[XmlEnum(Name="Kiribati")]
		Kiribati,
		[XmlEnum(Name="KoreaNorth")]
		KoreaNorth,
		[XmlEnum(Name="KoreaSouth")]
		KoreaSouth,
		[XmlEnum(Name="Kuwait")]
		Kuwait,
		[XmlEnum(Name="Kyrgyzstan")]
		Kyrgyzstan,
		[XmlEnum(Name="Laos")]
		Laos,
		[XmlEnum(Name="Latvia")]
		Latvia,
		[XmlEnum(Name="Lebanon")]
		Lebanon,
		[XmlEnum(Name="Lesotho")]
		Lesotho,
		[XmlEnum(Name="Liberia")]
		Liberia,
		[XmlEnum(Name="Libya")]
		Libya,
		[XmlEnum(Name="Liechtenstein")]
		Liechtenstein,
		[XmlEnum(Name="Lithuania")]
		Lithuania,
		[XmlEnum(Name="Luxembourg")]
		Luxembourg,
		[XmlEnum(Name="Macau")]
		Macau,
		[XmlEnum(Name="MacedoniaFormerYugRep")]
		MacedoniaFormerYugRep,
		[XmlEnum(Name="Madagascar")]
		Madagascar,
		[XmlEnum(Name="Malawi")]
		Malawi,
		[XmlEnum(Name="Malaysia")]
		Malaysia,
		[XmlEnum(Name="Maldives")]
		Maldives,
		[XmlEnum(Name="Mali")]
		Mali,
		[XmlEnum(Name="Malta")]
		Malta,
		[XmlEnum(Name="MarshallIslands")]
		MarshallIslands,
		[XmlEnum(Name="Martinique")]
		Martinique,
		[XmlEnum(Name="Mauritania")]
		Mauritania,
		[XmlEnum(Name="Mauritius")]
		Mauritius,
		[XmlEnum(Name="Mayotte")]
		Mayotte,
		[XmlEnum(Name="Micronesia")]
		Micronesia,
		[XmlEnum(Name="MidwayIslands")]
		MidwayIslands,
		[XmlEnum(Name="Mexico")]
		Mexico,
		[XmlEnum(Name="Moldova")]
		Moldova,
		[XmlEnum(Name="Monaco")]
		Monaco,
		[XmlEnum(Name="Mongolia")]
		Mongolia,
		[XmlEnum(Name="Montenegro")]
		Montenegro,
		[XmlEnum(Name="Montserrat")]
		Montserrat,
		[XmlEnum(Name="Morocco")]
		Morocco,
		[XmlEnum(Name="Mozambique")]
		Mozambique,
		[XmlEnum(Name="Myanmar")]
		Myanmar,
		[XmlEnum(Name="Nauru")]
		Nauru,
		[XmlEnum(Name="Namibia")]
		Namibia,
		[XmlEnum(Name="Nepal")]
		Nepal,
		[XmlEnum(Name="NetherlandsAntilles")]
		NetherlandsAntilles,
		[XmlEnum(Name="Netherlands")]
		Netherlands,
		[XmlEnum(Name="NewCaledonia")]
		NewCaledonia,
		[XmlEnum(Name="NewZealand")]
		NewZealand,
		[XmlEnum(Name="Nicaragua")]
		Nicaragua,
		[XmlEnum(Name="Niger")]
		Niger,
		[XmlEnum(Name="Nigeria")]
		Nigeria,
		[XmlEnum(Name="Niue")]
		Niue,
		[XmlEnum(Name="NorfolkIsland")]
		NorfolkIsland,
		[XmlEnum(Name="NorthernMarianaIslands")]
		NorthernMarianaIslands,
		[XmlEnum(Name="Norway")]
		Norway,
		[XmlEnum(Name="Oman")]
		Oman,
		[XmlEnum(Name="Pakistan")]
		Pakistan,
		[XmlEnum(Name="Palau")]
		Palau,
		[XmlEnum(Name="Palestine")]
		Palestine,
		[XmlEnum(Name="Panama")]
		Panama,
		[XmlEnum(Name="PapuaNewGuinea")]
		PapuaNewGuinea,
		[XmlEnum(Name="Paraguay")]
		Paraguay,
		[XmlEnum(Name="Peru")]
		Peru,
		[XmlEnum(Name="Philippines")]
		Philippines,
		[XmlEnum(Name="PitcairnIsland")]
		PitcairnIsland,
		[XmlEnum(Name="Poland")]
		Poland,
		[XmlEnum(Name="PuertoRico")]
		PuertoRico,
		[XmlEnum(Name="Qatar")]
		Qatar,
		[XmlEnum(Name="Reunion")]
		Reunion,
		[XmlEnum(Name="Romania")]
		Romania,
		[XmlEnum(Name="Russia")]
		Russia,
		[XmlEnum(Name="Rwanda")]
		Rwanda,
		[XmlEnum(Name="SamoaWestern")]
		SamoaWestern,
		[XmlEnum(Name="SamoaAmerica")]
		SamoaAmerica,
		[XmlEnum(Name="SanMarino")]
		SanMarino,
		[XmlEnum(Name="SaoTomeAndPrincipe")]
		SaoTomeAndPrincipe,
		[XmlEnum(Name="SaudiArabia")]
		SaudiArabia,
		[XmlEnum(Name="Senegal")]
		Senegal,
		[XmlEnum(Name="Serbia")]
		Serbia,
		[XmlEnum(Name="Seychelles")]
		Seychelles,
		[XmlEnum(Name="SierraLeone")]
		SierraLeone,
		[XmlEnum(Name="Singapore")]
		Singapore,
		[XmlEnum(Name="Slovakia")]
		Slovakia,
		[XmlEnum(Name="Slovenia")]
		Slovenia,
		[XmlEnum(Name="SolomonIslands")]
		SolomonIslands,
		[XmlEnum(Name="Somalia")]
		Somalia,
		[XmlEnum(Name="SouthAfrica")]
		SouthAfrica,
		[XmlEnum(Name="Spain")]
		Spain,
		[XmlEnum(Name="SriLanka")]
		SriLanka,
		[XmlEnum(Name="StHelena")]
		StHelena,
		[XmlEnum(Name="StKittsAndNevis")]
		StKittsAndNevis,
		[XmlEnum(Name="StLucia")]
		StLucia,
		[XmlEnum(Name="StVincentAndTheGrenadines")]
		StVincentAndTheGrenadines,
		[XmlEnum(Name="Sudan")]
		Sudan,
		[XmlEnum(Name="Suriname")]
		Suriname,
		[XmlEnum(Name="SvalbardAndJanMayenIslands")]
		SvalbardAndJanMayenIslands,
		[XmlEnum(Name="Swaziland")]
		Swaziland,
		[XmlEnum(Name="Sweden")]
		Sweden,
		[XmlEnum(Name="Switzerland")]
		Switzerland,
		[XmlEnum(Name="Syria")]
		Syria,
		[XmlEnum(Name="Tahiti")]
		Tahiti,
		[XmlEnum(Name="Taiwan")]
		Taiwan,
		[XmlEnum(Name="Tajikistan")]
		Tajikistan,
		[XmlEnum(Name="Tanzania")]
		Tanzania,
		[XmlEnum(Name="Thailand")]
		Thailand,
		[XmlEnum(Name="TimorLeste")]
		TimorLeste,
		[XmlEnum(Name="Togo")]
		Togo,
		[XmlEnum(Name="TrinidadAndTobago")]
		TrinidadAndTobago,
		[XmlEnum(Name="Tunisia")]
		Tunisia,
		[XmlEnum(Name="Turkey")]
		Turkey,
		[XmlEnum(Name="Turkmenistan")]
		Turkmenistan,
		[XmlEnum(Name="TurksAndCaicosIslands")]
		TurksAndCaicosIslands,
		[XmlEnum(Name="Tuvalu")]
		Tuvalu,
		[XmlEnum(Name="Uganda")]
		Uganda,
		[XmlEnum(Name="Ukraine")]
		Ukraine,
		[XmlEnum(Name="UnitedArabEmirates")]
		UnitedArabEmirates,
		[XmlEnum(Name="UpperVolta")]
		UpperVolta,
		[XmlEnum(Name="Uruguay")]
		Uruguay,
		[XmlEnum(Name="Uzbekistan")]
		Uzbekistan,
		[XmlEnum(Name="Vanuatu")]
		Vanuatu,
		[XmlEnum(Name="Vatican")]
		Vatican,
		[XmlEnum(Name="Venezuela")]
		Venezuela,
		[XmlEnum(Name="Vietnam")]
		Vietnam,
		[XmlEnum(Name="VirginIslands")]
		VirginIslands,
		[XmlEnum(Name="WakeIsland")]
		WakeIsland,
		[XmlEnum(Name="WallisAndFutunaIslands")]
		WallisAndFutunaIslands,
		[XmlEnum(Name="WesternSahara")]
		WesternSahara,
		[XmlEnum(Name="WesternSamoa")]
		WesternSamoa,
		[XmlEnum(Name="Yemen")]
		Yemen,
		[XmlEnum(Name="Zaire")]
		Zaire,
		[XmlEnum(Name="Zambia")]
		Zambia,
		[XmlEnum(Name="Zimbabwe")]
		Zimbabwe,
	}
}
